<?php

/**
 * Страница настроек в админке, и блок для вывода формы
 * @file
 * Module file for Piwik proxy module
 * @todo Облагородить код, написать комментарии.
 * $Id$
 */

/**
 * Implements hook_menu().
 */
function piwik_proxy_menu() {
  $items['admin/config/services/piwik_proxy'] = array(//Адрес страницы администрирования
    'title' => 'Piwik proxy', // Тайтл страницы
    'page callback' => 'drupal_get_form', //функция, отвечающая за вывод страницы
    'page arguments' => array('piwik_proxy_form'), // аргумент hook_form()
    'access arguments' => array('administer users'), // права доступа
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_form().
 * Admin form to configurable piwik_proxy
 */
function piwik_proxy_form($form, &$form_state) {
  // Check library file.
  $library = DRUPAL_ROOT . '/sites/all/libraries/piwik-tracker-proxy/piwik.php';
  if (!file_exists($library)) {
    drupal_set_message('Download ​<a href ="https://github.com/piwik/tracker-proxy/archive/master.zip">archive</a> or a <a href ="https://raw.githubusercontent.com/piwik/tracker-proxy/master/piwik.php">file directly</a>.');
    drupal_set_message('Place piwik.php into a new folder in the following location:<br />');
    drupal_set_message('sites/all/libraries/piwik-tracker-proxy<br />');
    drupal_set_message('So the actual library can be found at:<br />');
    drupal_set_message('sites/all/libraries/piwik-tracker-proxy/piwik.php<br />');
  }
  else {
    $form['piwikProxySiteID'] = array(
      '#type' => 'textfield',
      '#title' => t('Piwik site ID'),
      '#size' => 3,
      '#maxlength' => 3,
      '#required' => TRUE,
      '#default_value' => variable_get('piwikProxySiteID'), //дёргаем системную переменную
      '#description' => t("Go to Piwik &raquo; Settings &raquo; Websites &raquo; enter the appropriate site ID from the table of websites."),
    );

    $form['piwikUrl'] = array(
      '#type' => 'textfield',
      '#title' => t('Piwik URL'),
      '#size' => 50,
      '#maxlength' => 50,
      '#required' => TRUE,
      '#default_value' => variable_get('piwikUrl'),
      '#description' => t('Should contain the URL to your Piwik server, e.g, http://mysite.com/piwik/'),
    );

    $form['piwikProxyTokenAuth'] = array(
      '#type' => 'textfield',
      '#title' => t('Token auth'),
      '#size' => 50,
      '#maxlength' => 50,
      '#required' => TRUE,
      '#default_value' => variable_get('piwikProxyTokenAuth'),
      '#description' => t('In your Piwik server:<br />&#8226;login as Super user<br />&#8226;create a user, set the login for example: "UserTrackingAPI"<br />&#8226;assign this user admin permission on all websites you wish to track<br />&#8226;copy the <strong>token_auth</strong> for this user: you will use it later'),
    );

//чекбокс подменять URL или нет
    $form['piwikProxyHidePath'] = array(
      '#type' => 'checkbox',
      '#title' => 'Hide path to file',
      '#default_value' => variable_get('piwikProxyHidePath', FALSE),
      '#description' => t('Hide path to piwik.php file from AdBlock. <strong> Note!</strong> You want to edit the configuration files of Your web server.'),
    );
    // поле появляется только в случае TRUE в предыдущем
    $form['piwikProxyFalsePath'] = array(
      '#type' => 'textfield',
      '#title' => t('False path'),
      '#size' => 50,
      '#maxlength' => 50,
      '#description' => t('False path to piwik.php, e.g. somedir/somefile.php'),
      '#default_value' => variable_get('piwikProxyFalsePath'),
      '#states' => array(
        'visible' => array(
          'input[name="piwikProxyHidePath"]' => array('checked' => TRUE)
        )
      ),
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Save settings'),
        //'#submit' => TRUE,
    );
  }

  @$piwikProxyHidePath = variable_get('piwikProxyHidePath');
  @$piwikProxyFalsePath = variable_get('piwikProxyFalsePath');
  //если отмечен чекбокс ProxyHide и введена строка piwikProxyFalsePath
  if (($piwikProxyHidePath == TRUE) && isset($piwikProxyFalsePath)) {
    $form['#prefix'] = '<strong>Rewrite rule for NGINX</strong><br />Insert this code to the nginx config file after "location" directive inside braces of virtual host where Your Drupal site installation:' . '<div style="overflow: auto; display: block; color:#00FF00; background-color:#000000; position: relative; border: solid 1px #666666;  "><pre><code>' . 'rewrite  ^/' . $piwikProxyFalsePath . '  ' . $GLOBALS['base_path'] . 'sites/all/libraries/piwik-tracker-proxy/piwik.php  last;' . '</code></pre></div>Sample:';
    $form['#prefix'] .= '<div style="overflow: auto; display: block; color:#00FF00; background-color:#000000; position: relative; border: solid 1px #666666;  "><pre><code>' . "location / {\n" . '     rewrite  ^/' . $piwikProxyFalsePath . '  ' . $GLOBALS['base_path'] . 'sites/all/libraries/piwik-tracker-proxy/piwik.php  last;' . '</code></pre></div>';
  }

  @$piwikProxyCode = variable_get('piwikProxyCode');
  //Если есть готовый код, выводим helper в суффиксе формы
  if (isset($piwikProxyCode)) {
    $form['#suffix'] = '<strong>Helper</strong><br />Use this code for third-party engines, such as forums, wiki, raw html, etc.' . '<div style="overflow: auto; display: block; color:#00FF00; background-color:#000000; position: relative; border: solid 1px #666666;  "><pre><code>' . '&lt;script type="text/javascript"&gt;' . "\n" . variable_get('piwikProxyCode') . "\n&lt;/script&gt;" . '</code></pre></div><span style="color:red">Do not</span> insert this code in Your Drupal site!';
  }
  return $form; //Важно! Отправлять всё, а не system_settings_form($form), 
}

/**
 * Функция сабмита формы. Выполняется вычисление и занесение переменных помимо формы.
 * Пишется конфигурационный файл.
 * @param array $form
 * @param array $form_state
 */
function piwik_proxy_form_submit($form, &$form_state) {
  // Сабмитим переменные из полей
  variable_set('piwikProxySiteID', $form['piwikProxySiteID']['#value']);
  variable_set('piwikProxyTokenAuth', $form['piwikProxyTokenAuth']['#value']);
  variable_set('piwikUrl', $form['piwikUrl']['#value']);
  variable_set('piwikProxyHidePath', $form['piwikProxyHidePath']['#value']);
  variable_set('piwikProxyFalsePath', $form['piwikProxyFalsePath']['#value']);

  $file = DRUPAL_ROOT . '/sites/all/libraries/piwik-tracker-proxy/config.php';
  $targetFile = fopen($file, 'w') or drupal_set_message("can't open file");
  fwrite($targetFile, "<?php\n"); //выводим в файл
  fwrite($targetFile, "\$PIWIK_URL = '" . variable_get('piwikUrl') . "';\n"); //выводим в файл
  fwrite($targetFile, "\$TOKEN_AUTH = '" . variable_get('piwikProxyTokenAuth') . "';\n"); //выводим в файл
  fwrite($targetFile, '$timeout = 5' . ";\n"); //выводим в файл
  fclose($targetFile); //закрываем
//Если путь не подменяется
  if (variable_get('piwikProxyHidePath') == FALSE) {

    //Получаем из настроек переменные
    $siteID = variable_get('piwikProxySiteID');
    $proxyUrl = $GLOBALS['base_url'] . '/sites/all/libraries/piwik-tracker-proxy/';
    $proxyUrl = preg_replace('%(.*//)(.*)%', '$2', $proxyUrl);

    $codeContent = 'var _paq = _paq || [];' . "\n";
    $codeContent .= "  _paq.push(['trackPageView']);" . "\n";
    $codeContent .= "  _paq.push(['enableLinkTracking']);" . "\n";
    $codeContent .= '  (function() {' . "\n";
    $codeContent .= '   var u="//' . $proxyUrl . '";' . "\n";
    $codeContent .= "   _paq.push(['setTrackerUrl', u+'piwik.php']);" . "\n";
    $codeContent .= "   _paq.push(['setSiteId', " . $siteID . ']);' . "\n";
    $codeContent .= "   var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];" . "\n";
    $codeContent .= "   g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.php'; s.parentNode.insertBefore(g,s);" . "\n";
    $codeContent .= '  })();';
  }
  else {

    //Получаем из настроек переменные
    $siteID = variable_get('piwikProxySiteID');
    $falsePath = variable_get('piwikProxyFalsePath');
    $proxyUrl = $GLOBALS['base_root'] . '/' . $falsePath;
    $proxyUrl = preg_replace('%(.*//)(.*)%', '$2', $proxyUrl);

    $codeContent = 'var _paq = _paq || [];' . "\n";
    $codeContent .= "  _paq.push(['trackPageView']);" . "\n";
    $codeContent .= "  _paq.push(['enableLinkTracking']);" . "\n";
    $codeContent .= '  (function() {' . "\n";
    $codeContent .= '   var u="//' . $proxyUrl . '";' . "\n";
    $codeContent .= "   _paq.push(['setTrackerUrl', u]);" . "\n";
    $codeContent .= "   _paq.push(['setSiteId', " . $siteID . ']);' . "\n";
    $codeContent .= "   var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];" . "\n";
    $codeContent .= "   g.type='text/javascript'; g.async=true; g.defer=true; g.src=u; s.parentNode.insertBefore(g,s);" . "\n";
    $codeContent .= '  })();';
  }

  variable_set('piwikProxyCode', $codeContent); //код в системную переменную
}

// Добавляем JS в footer
drupal_add_js(variable_get('piwikProxyCode'), array('type' => 'inline', 'scope' => 'footer', 'weight' => 0));
