<?php

/**
 * Страница настроек в админке, и блок для вывода формы
 * @file
 * Module file for Piwik proxy module
 * @TODO Сделать загрузку зависимостей из git.
 * @todo Облагородить код, написать комментарии.
 * $Id$
 */

/**
 * Implements hook_menu().
 */
function piwik_proxy_menu() {
  $items['admin/config/system/piwik_proxy'] = array(//Адрес страницы администрирования
    'title' => 'Piwik proxy', // Тайтл страницы
    'page callback' => 'drupal_get_form', //функция, отвечающая за вывод страницы
    'page arguments' => array('piwik_proxy_form'), // аргумент hook_form()
    'access arguments' => array('administer users'), // права доступа
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_form().
 * Admin form to configurable piwik_proxy
 */
function piwik_proxy_form($form, &$form_state) {
  $form['piwikProxySiteID'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik site ID'),
    '#size' => 3,
    '#maxlength' => 3,
    '#required' => TRUE,
    '#default_value' => variable_get('piwikProxySiteID'), //дёргаем системную переменную
  );

  $form['piwikUrl'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik URL'),
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
    '#default_value' => variable_get('piwikUrl'),
  );

  $form['piwikProxyTokenAuth'] = array(
    '#type' => 'textfield',
    '#title' => t('Token auth'),
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
    '#default_value' => variable_get('piwikProxyTokenAuth'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
      //'#submit' => TRUE,
  );
  //return system_settings_form($form);
  return $form; //Важно! Отправлять всё, а не system_settings_form($form), 
  //чтобы произошёл вызов piwik_proxy_form_submit($form, &$form_state)!
}

/**
 * Функция сабмита формы. Выполняется вычисление и занесение переменных помимо формы.
 * Пишется конфигурационный файл.
 * @param array $form
 * @param array $form_state
 */
function piwik_proxy_form_submit($form, &$form_state) {
  variable_set('piwikProxySiteID', $form['piwikProxySiteID']['#value']);
  variable_set('piwikProxyTokenAuth', $form['piwikProxyTokenAuth']['#value']);
  variable_set('piwikUrl', $form['piwikUrl']['#value']);

  $file = DRUPAL_ROOT . '/sites/all/libraries/piwik/config.php';
  $targetFile = fopen($file, 'w') or drupal_set_message("can't open file");
  fwrite($targetFile, "<?php\n"); //выводим в файл
  fwrite($targetFile, "\$PIWIK_URL = '" . variable_get('piwikUrl') . "';\n"); //выводим в файл
  fwrite($targetFile, "\$TOKEN_AUTH = '" . variable_get('piwikProxyTokenAuth') . "';\n"); //выводим в файл
  fwrite($targetFile, '$timeout = 5' . ";\n"); //выводим в файл
  fclose($targetFile); //закрываем
  //Получаем из настроек переменные
  $siteID = variable_get('piwikProxySiteID');
  $proxyUrl = $GLOBALS['base_url'] . '/sites/all/libraries/piwik/';
  $proxyUrl = preg_replace('%(.*//)(.*)%', '$2', $proxyUrl);

  $htmlContent = '<script type="text/javascript">' . "\n";
  $htmlContent .= 'var _paq = _paq || [];' . "\n";
  $htmlContent .= "  _paq.push(['trackPageView']);" . "\n";
  $htmlContent .= "  _paq.push(['enableLinkTracking']);" . "\n";
  $htmlContent .= '  (function() {' . "\n";
  $htmlContent .= '   var u="//' . $proxyUrl . '";' . "\n";
  $htmlContent .= "   _paq.push(['setTrackerUrl', u+'piwik.php']);" . "\n";
  $htmlContent .= "   _paq.push(['setSiteId', " . $siteID . ']);' . "\n";
  $htmlContent .= "   var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];" . "\n";
  $htmlContent .= "   g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.php'; s.parentNode.insertBefore(g,s);" . "\n";
  $htmlContent .= '  })();' . "\n";
  $htmlContent .= '</script>' . "\n";
  variable_set('piwikProxyCode', $htmlContent);
}

/**
 * Функция настройки блока
 * Implements hook_block_info().
 */
function piwik_proxy_block_info() {
  $blocks['commentsView'] = array(
    'info' => t('Piwik proxy code'), //название блока в admin/structure/blocks
//    'cache' => DRUPAL_CACHE_GLOBAL, //Режим кэша
    'cache' => DRUPAL_NO_CACHE, //Режим кэша
  );
  return $blocks;
}

/**
 * Функция отображения блока
 * @return array Содержимое блока
 */
function piwik_proxy_block_view() {
  $block = array();
  //$block['subject'] = t('Piwik Proxy code'); //Заголовок блока
  $block['content'] = variable_get('piwikProxyCode');
  return $block;
}
